

name: Stage Build 

on:
  # "On merge" to stage is effectively a push to the stage branch after a PR is merged
  push:
    branches:
      - stage
  # allow manual runs
  workflow_dispatch:

jobs:
  build:
    name: Build app on stage
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Enable Corepack and setup pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          # Add all runtime env vars your build needs here
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          # SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }} # if you actually need it during build
        run: pnpm build

      - name: Upload build artifacts (Next.js)
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: |
            .next
            out
            dist
          if-no-files-found: warn